<?xml version="1.0" encoding="UTF-8"?>

<workspace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workingsets.xsd">
  <projects>
    <project>
      <name>bsp_K60F120M</name>
      <path>..\..\..\mqx\build\cw10\bsp_K60F120M</path>
      <open>true</open>
      <activeconfig>Debug</activeconfig>
      <buildreferences config="Debug">false</buildreferences>
      <buildreferences config="Release">false</buildreferences>
    </project>
    <project>
      <name>mfs_K60F120M</name>
      <path>..\..\..\mfs\build\cw10\mfs_K60F120M</path>
      <open>true</open>
      <reference>bsp_K60F120M</reference>
      <reference>psp_K60F120M</reference>
      <activeconfig>Debug</activeconfig>
      <buildreferences config="Debug">false</buildreferences>
      <buildreferences config="Release">false</buildreferences>
    </project>
    <project>
      <name>psp_K60F120M</name>
      <path>..\..\..\mqx\build\cw10\psp_K60F120M</path>
      <open>true</open>
      <activeconfig>Debug</activeconfig>
      <buildreferences config="Debug">false</buildreferences>
      <buildreferences config="Release">false</buildreferences>
    </project>
    <project>
      <name>rtcs_K60F120M</name>
      <path>..\..\..\rtcs\build\cw10\rtcs_K60F120M</path>
      <open>true</open>
      <reference>bsp_K60F120M</reference>
      <reference>mfs_K60F120M</reference>
      <reference>psp_K60F120M</reference>
      <activeconfig>Debug</activeconfig>
      <buildreferences config="Debug">false</buildreferences>
      <buildreferences config="Release">false</buildreferences>
    </project>
    <project>
      <name>shell_K60F120M</name>
      <path>..\..\..\shell\build\cw10\shell_K60F120M</path>
      <open>true</open>
      <reference>bsp_K60F120M</reference>
      <reference>mfs_K60F120M</reference>
      <reference>psp_K60F120M</reference>
      <reference>rtcs_K60F120M</reference>
      <activeconfig>Debug</activeconfig>
      <buildreferences config="Debug">false</buildreferences>
      <buildreferences config="Release">false</buildreferences>
    </project>
    <project>
      <name>usbd_K60F120M</name>
      <path>..\..\..\usb\device\build\cw10\usbd_K60F120M</path>
      <open>true</open>
      <reference>bsp_K60F120M</reference>
      <reference>mfs_K60F120M</reference>
      <reference>psp_K60F120M</reference>
      <activeconfig>Debug</activeconfig>
      <buildreferences config="Debug">false</buildreferences>
      <buildreferences config="Release">false</buildreferences>
    </project>
    <project>
      <name>usbh_K60F120M</name>
      <path>..\..\..\usb\host\build\cw10\usbh_K60F120M</path>
      <open>true</open>
      <reference>bsp_K60F120M</reference>
      <reference>mfs_K60F120M</reference>
      <reference>psp_K60F120M</reference>
      <activeconfig>Debug</activeconfig>
      <buildreferences config="Debug">false</buildreferences>
      <buildreferences config="Release">false</buildreferences>
    </project>
  </projects>
  <workingsets>
    <workingSet editPageId="org.eclipse.cdt.ui.CElementWorkingSetPage" id="1323268527287_1" label="K60F120M" name="K60F120M"> 
      <item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/bsp_K60F120M" type="4"/>  
      <item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/psp_K60F120M" type="4"/>  
      <item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/rtcs_K60F120M" type="4"/>  
      <item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/mfs_K60F120M" type="4"/>  
      <item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/shell_K60F120M" type="4"/>  
      <item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/usbd_K60F120M" type="4"/>  
      <item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/usbh_K60F120M" type="4"/> 
    </workingSet>
  </workingsets>
  <cdtconfigurations>
    <workingSet name="K60F120M"> 
      <config name="Release"> 
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.1738784430" name="psp_K60F120M" configName="Release"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.1738784430" name="mfs_K60F120M" configName="Release"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.1738784430" name="rtcs_K60F120M" configName="Release"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.1738784430" name="bsp_K60F120M" configName="Release"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.1738784430" name="shell_K60F120M" configName="Release"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.1738784430" name="usbd_K60F120M" configName="Release"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.1738784430" name="usbh_K60F120M" configName="Release"/> 
      </config>  
      <config name="Debug"> 
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.231439194" name="psp_K60F120M" configName="Debug"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.231439194" name="mfs_K60F120M" configName="Debug"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.231439194" name="rtcs_K60F120M" configName="Debug"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.231439194" name="bsp_K60F120M" configName="Debug"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.231439194" name="shell_K60F120M" configName="Debug"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.231439194" name="usbd_K60F120M" configName="Debug"/>  
        <project config="com.freescale.arm.cdt.toolchain.config.arm.release.231439194" name="usbh_K60F120M" configName="Debug"/> 
      </config> 
    </workingSet>
  </cdtconfigurations>
</workspace>
